name: application
version: 1
summary: Qt Application Example
description: A simple text editor
confinement: devmode

apps:
  application:
    command: ubuntu-app-launch application
    plugs: [ubuntu-app-runtime, unity7, home]

parts:
  application:
    source: src/
    plugin: qmake
    qt-version: qt5
    after: [ubuntu-app-runtime, qt5]
  ubuntu-app-runtime:
    source: .
    plugin: make
    make-parameters: ["SRC_DIR=../src"]

